### ISSUE TITLE
Add typings for imports in Typescript

### ISSUE THREAD

**Issue by electrovir** [ehmicky/human-signals#2]
Getting a `Could not find a declaration file for module 'human-signals'.` when importing this in Typescript, such as in the following:

```typescript
import {signalsByName} from 'human-signals';
```

Also `@types/human-signals` does not exist in npm.

Happy to assist if needed.

**Comment by ehmicky** [comment]
Hi @electrovir,
Absolutely, types would be a great idea!

This might be a little tricky since the properties of the exported objects is dynamic as it depends on `process.platform`.

This probably should be either a `src/main.ts.d` ambient file or a `@types/human-signals` package (as opposed to either rewriting `*.js` to `*.ts`).

If you want to give it a go, please let me know!

**Comment by electrovir** [comment]
I was thinking a `.d.ts` file actually in the repo of some sort would be best, like you mentioned as an option.

I'll take a crack at it! I just started using this package so I can test it in actual use. I'll put it in `src/main.d.ts` as you suggested :)

**Comment by ehmicky** [comment]
Thanks for the PR!
The release is pending due to [a bug in Node.js `13.10.0`](https://github.com/sindresorhus/got/issues/1107) which should be fixed anytime soon.

**Comment by electrovir** [comment]
You're welcome, it was fun! 🎉

**Comment by ehmicky** [comment]
Released in [`2.1.0`](https://github.com/ehmicky/human-signals/releases/tag/2.1.0)!

**Comment by electrovir** [comment]
Finally got around to updating. Looks good, thanks!
