### ISSUE TITLE
 Cannot destructure property 'signals' of '_os.constants' as it is undefined.

### ISSUE THREAD

**Issue by jasp402** [ehmicky/human-signals#22]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

![image](https://github.com/ehmicky/human-signals/assets/8978470/48c09de6-1a14-477d-9fc1-c6ac129e8e8b)
When trying to run cypress I get this error. but the problem is generated where the image shows

### Steps to reproduce

Cypress v13.2.0 is installed
a simple test case is created
and it runs and the error is shown

### Configuration

I don't know

### Environment

I don't know

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @jasp402,

Thanks for reaching out.

`human-signals` must be run in a Node.js environment, because the list of signals is using `node:os`.

https://github.com/ehmicky/human-signals/blob/326e89eafedcb74fb67097677a3a595a8e1ba8f9/src/signals.js#L1

Your environment is missing Node.js core modules (`_os` is `undefined`). It is not an issue with `human-signals` but with your setup of Cypress.
